#!/usr/bin/env node
/**
 * scripts/run-tests.js
 *
 * Runs the architectural-invariant test suite.
 *
 * The tests verify the cures applied across all four audit rounds.
 * They run against an in-memory SQLite (sql.js), so they're fast and
 * have no native dependencies — `pnpm install && pnpm test` works
 * anywhere Node runs.
 *
 * Why this wrapper exists:
 * The project ships a SvelteKit-shaped tsconfig.json that extends
 * .svelte-kit/tsconfig.json (a file generated by `svelte-kit sync`).
 * In CI before svelte-kit has run, that path doesn't exist, and
 * vitest's underlying esbuild errors out trying to resolve it. The
 * wrapper temporarily moves the project tsconfig out of the way so
 * the tests use their own tests/tsconfig.json instead. This keeps
 * the test runner standalone — no `svelte-kit sync` required.
 */
import { execSync } from 'node:child_process';
import { existsSync, renameSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const TO_HIDE = [
  'tsconfig.json',
  'vite.config.ts',
  'postcss.config.js',
  'svelte.config.js'
];

function hide(file) {
  const src = resolve(ROOT, file);
  const dst = src + '.test-bak';
  if (existsSync(src)) renameSync(src, dst);
}

function unhide(file) {
  const dst = resolve(ROOT, file + '.test-bak');
  const src = resolve(ROOT, file);
  if (existsSync(dst)) renameSync(dst, src);
}

let exitCode = 0;
try {
  TO_HIDE.forEach(hide);
  execSync('node node_modules/.bin/vitest run --reporter=verbose', {
    cwd: ROOT,
    stdio: 'inherit'
  });
} catch (err) {
  exitCode = err.status ?? 1;
} finally {
  TO_HIDE.forEach(unhide);
}

process.exit(exitCode);
